/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: onlmee (https://sketchfab.com/onlmee)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/lizard-caabb275738d44bdb93d0b1f40ac5dd0
title: Lizard
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/lizard.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 5, 0, 0]}>
        <group position={[0, 20, -20]}>
          <mesh
            geometry={nodes.Object_2.geometry}
            material={materials.wire_012008018}
          />
          <mesh
            geometry={nodes.Object_3.geometry}
            material={materials.wire_000000000}
          />
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials.wire_022010008}
          />
          <mesh
            geometry={nodes.Object_5.geometry}
            material={materials.wire_088199225}
          />
          <mesh
            geometry={nodes.Object_6.geometry}
            material={materials.wire_177088027}
          />
          <mesh
            geometry={nodes.Object_7.geometry}
            material={materials.wire_006135058}
          />
          <mesh
            geometry={nodes.Object_8.geometry}
            material={materials.wire_006135058}
          />
          <mesh
            geometry={nodes.Object_9.geometry}
            material={materials.wire_135006006}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/lizard.gltf");
